application:
  customProperty: false
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelogdb/db.changelog-master.yaml
    enabled: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
logging:
  level:
    root: info
